//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string Fırma_Adı { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Vergi_No { get; set; }
        public string Banka_HesapNo { get; set; }
        public Nullable<bool> Active_fl { get; set; }
        public string EPosta { get; set; }
        public string Yetkılı { get; set; }
        public string Yetkılı_cep { get; set; }
        public string Fax { get; set; }
        public string Nott { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<decimal> Odeme { get; set; }
        public Nullable<decimal> Iptal { get; set; }
        public Nullable<System.DateTime> CredateTıme { get; set; }
    }
}
