//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> FIYATHG { get; set; }
        public Nullable<decimal> FIYATMAT { get; set; }
        public Nullable<decimal> CAM { get; set; }
        public Nullable<decimal> CAM2 { get; set; }
        public Nullable<decimal> CAM4 { get; set; }
        public Nullable<decimal> CAM6 { get; set; }
        public Nullable<decimal> CAM8 { get; set; }
    }
}
