//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsColor
    {
        public int id { get; set; }
        public string MALZEME { get; set; }
        public string MCINS { get; set; }
        public string TUKETIM { get; set; }
        public string MEVCUT { get; set; }
        public string BIRIM { get; set; }
        public string HEPSİ { get; set; }
        public string KESİLEN { get; set; }
    }
}
