//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string BARKOD { get; set; }
        public string URUNADI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> SONFIYAT { get; set; }
        public Nullable<decimal> ALISFIYATI { get; set; }
        public Nullable<decimal> STOK_DURUMU { get; set; }
        public Nullable<bool> EKLEME { get; set; }
        public Nullable<int> UYARI_SAYISI { get; set; }
        public string BIRIM { get; set; }
        public string GRUP { get; set; }
        public string KDV { get; set; }
        public Nullable<decimal> INDIRIMLI_FIYAT { get; set; }
        public Nullable<bool> STOK_TAKIP { get; set; }
    }
}
