//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CncTicariOtomasyonEntities : DbContext
    {
        public CncTicariOtomasyonEntities()
            : base("name=CncTicariOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Satıslar> Satıslar { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Warehouse> WareHouses { get; set; }
        public virtual DbSet<WorkPlace> WorkPlaces { get; set; }
        public virtual DbSet<SpecialCode> SpecialCodes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Bolumler> Bolumlers { get; set; }
        public virtual DbSet<Isyeri> Isyeris { get; set; }
        public virtual DbSet<SıpDurumu> SıpDurumu { get; set; }
        public virtual DbSet<Orfiche> Orfiches { get; set; }
        public virtual DbSet<Orfline> Orflines { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsColor> ItemsColors { get; set; }
        public virtual DbSet<SıparısAppPool> SıparısAppPool { get; set; }
    }
}
