//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orfiche
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FisNo { get; set; }
        public string BarkodNo { get; set; }
        public string SiparisSekli { get; set; }
        public string BID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public string BelgeNo { get; set; }
        public Nullable<int> OzelKod { get; set; }
        public Nullable<int> Bölüm { get; set; }
        public Nullable<int> Departman { get; set; }
        public Nullable<int> Isyeri { get; set; }
        public Nullable<int> SiparisDurumu { get; set; }
        public Nullable<double> ToplamIndirim { get; set; }
        public Nullable<double> TasarimTutari { get; set; }
        public Nullable<double> KargoTutari { get; set; }
        public Nullable<double> Toplam { get; set; }
        public Nullable<double> NetTutar { get; set; }
    }
}
