//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orfline
    {
        public int Id { get; set; }
        public string OrficheNo { get; set; }
        public int MalzemeKodu { get; set; }
        public string MalzemeAdi { get; set; }
        public string Ozellik { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> En { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> M2 { get; set; }
        public Nullable<double> M2Fiyat { get; set; }
        public Nullable<double> Fiyat { get; set; }
    }
}
