//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Sıpmasdet
    {
        public string FisNo { get; set; }
        public string Fırma_Adı { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public string BarkodNo { get; set; }
        public string SiparisSekli { get; set; }
        public Nullable<int> SiparisDurumu { get; set; }
        public int MalzemeKodu { get; set; }
        public string Ozellik { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<double> M2FIYAT { get; set; }
        public Nullable<int> ToplamAdet { get; set; }
    }
}
