//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satıslar
    {
        public int ID { get; set; }
        public string Alınanlar { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> ADET { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
        public Nullable<int> SATIS_NO { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public string TUR { get; set; }
        public string ODEME_TUTARI { get; set; }
        public string BIRIM { get; set; }
        public Nullable<short> TUR_ID { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> KULLANICI_ID { get; set; }
        public Nullable<System.DateTime> ODEME_ZAMANI { get; set; }
        public Nullable<bool> ODEME_HABER { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<decimal> ALIS_FIYATI { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<bool> FATURA { get; set; }
    }
}
