//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SıparısAppPool
    {
        public int id { get; set; }
        public string SipID { get; set; }
        public Nullable<bool> Kesim_fl { get; set; }
        public Nullable<int> PaletNo { get; set; }
        public Nullable<bool> Palet_fl { get; set; }
        public Nullable<bool> Pres_fl { get; set; }
        public bool Paket_fl { get; set; }
        public Nullable<decimal> Toplamİndirim { get; set; }
        public Nullable<decimal> TasarimTutari { get; set; }
        public Nullable<decimal> KargoTutari { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<decimal> NetTutar { get; set; }
        public Nullable<int> PaketSayı { get; set; }
        public Nullable<bool> Teslim_fl { get; set; }
        public Nullable<bool> Onay_fl { get; set; }
    }
}
