//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon.Models.CncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SıparısAppPoolView
    {
        public string SipID { get; set; }
        public Nullable<bool> Onay_fl { get; set; }
        public Nullable<bool> Kesim_fl { get; set; }
        public Nullable<int> PaletNo { get; set; }
        public Nullable<bool> Palet_fl { get; set; }
        public Nullable<bool> Pres_fl { get; set; }
        public bool Paket_fl { get; set; }
        public Nullable<int> PaketSayı { get; set; }
        public Nullable<bool> Teslim_fl { get; set; }
        public string MusterıAdı { get; set; }
        public string SiparisDurumu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public string Aciklama { get; set; }
        public string StokAdı { get; set; }
        public string RenkAdı { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> m2 { get; set; }
    }
}
